[CmdletBinding()]
param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$serverDirectory = Join-Path $repoRoot "tools/GM.Development.Mcp/bin/$Configuration/net10.0-windows"
$serverPath = Join-Path $serverDirectory 'GM.Development.Mcp.exe'
if (-not (Test-Path -LiteralPath $serverPath)) {
    throw 'Build the solution with scripts/verify.ps1 before configuring MCP.'
}

# JSON string quoting is also valid for these TOML basic string values.
$commandLiteral = ConvertTo-Json -InputObject $serverPath -Compress
$rootLiteral = ConvertTo-Json -InputObject $repoRoot -Compress
$directoryLiteral = ConvertTo-Json -InputObject $serverDirectory -Compress
$configDirectory = Join-Path $repoRoot '.codex'
$configPath = Join-Path $configDirectory 'config.toml'
$beginMarker = '# BEGIN GM Desktop development MCP (generated by scripts/setup-mcp.ps1)'
$endMarker = '# END GM Desktop development MCP'
$block = @"
$beginMarker
[mcp_servers.gmDesktop]
command = $commandLiteral
args = ["--repo-root", $rootLiteral, "--configuration", "$Configuration"]
cwd = $directoryLiteral
startup_timeout_sec = 30
tool_timeout_sec = 45
$endMarker
"@
$content = if (Test-Path -LiteralPath $configPath) { [IO.File]::ReadAllText($configPath) } else { '' }
$pattern = '(?ms)^' + [regex]::Escape($beginMarker) + '\r?\n.*?^' + [regex]::Escape($endMarker) + '\r?$'
if ([regex]::IsMatch($content, $pattern)) {
    $content = [regex]::Replace($content, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $block })
} elseif ($content.Contains($beginMarker) -or $content.Contains($endMarker) -or $content -match '(?m)^\s*\[\s*mcp_servers\.(gmDesktop|"gmDesktop"|''gmDesktop'')\s*\]') {
    throw 'Existing gmDesktop configuration is not a complete generated block. Review .codex/config.toml before replacing it.'
} else {
    $content = $content.TrimEnd() + "`r`n`r`n" + $block + "`r`n"
}
New-Item -ItemType Directory -Path $configDirectory -Force | Out-Null
[IO.File]::WriteAllText($configPath, $content, [Text.UTF8Encoding]::new($false))
Write-Host "Configured gmDesktop in $configPath"
Write-Host 'Reload MCP servers in Codex, or restart Codex, to discover the new tools.'
